package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"gql/graph/model"

	"github.com/google/uuid"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, text string) (*model.Todo, error) {
	newTodo := &model.Todo{
		ID:   uuid.New().String(),
		Text: text,
		Done: false,
	}

	if err := r.DB.Create(newTodo).Error; err != nil {
		return nil, err
	}

	r.Mu.Lock()
	for _, ch := range r.Subscriber {
		select {
		case ch <- newTodo:
		default:
		}
	}
	r.Mu.Unlock()

	return newTodo, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, done bool) (*model.Todo, error) {
	var todo model.Todo

	result := r.DB.Model(&todo).Where("id=?", id).Update("done", done)
	if result.Error != nil {
		return nil, result.Error
	}

	r.DB.First(&todo, "id=?", id)
	return &todo, nil
}

// DeleteTodo is the resolver for the deleteTodo field
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	result := r.DB.Delete(&model.Todo{}, "id=?", id)
	if result.Error != nil {
		return false, result.Error
	}
	return true, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	var todos []*model.Todo

	result := r.DB.Find(&todos)
	if result.Error != nil {
		return nil, result.Error
	}

	return todos, nil
}

// TodoAdded is the resolver for the todoAdded field.
func (r *subscriptionResolver) TodoAdded(ctx context.Context) (<-chan *model.Todo, error) {
	id := uuid.New().String()
	ch := make(chan *model.Todo, 1)

	r.Mu.Lock()
	if r.Subscriber == nil {
		r.Subscriber = make(map[string]chan *model.Todo)
	}
	r.Subscriber[id] = ch
	r.Mu.Unlock()

	go func() {
		<-ctx.Done()
		r.Mu.Lock()
		delete(r.Subscriber, id)
		r.Mu.Unlock()
	}()

	return ch, nil
}

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	// This doesn't hit the DB immediately; it waits to batch with others!
	return For(ctx).UserLoader.Load(ctx, obj.UserID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
